#!/bin/ksh
#
# Script: CreateCollectdInstance
# Date: Nov 2018
# Author: MGC
# Version: .1
# 
USER=collectd
GROUP=$USER
LV=collectdlv
VG=rootvg
FS=/opt/$USER
LVSIZE=1
TARFILE=collectd.tar 
HOSTNAME=`uname -n`

date

print " Create collectd LV "
mklv -t jfs2 -y $LV $VG $LVSIZE

print "Create the filesystem and mount on boot"
crfs -v jfs2 -d /dev/$LV -m $FS -A yes

print "Mount the $FS filesystem"
mount $FS

#expand to 1 GB space
chfs -asize=+1G $FS

# Create collectd group
mkgroup -A $GROUP

# Create application id with no login shell 
/usr/sbin/useradd -c "Collectd Monitoring System" -d /opt/$USER -m -g $GROUP -s /usr/bin/rksh93 -u 1001 $USER

